#!/usr/bin/python
"""

This file is just a wrapper for pdfCropMargins.py which allows the program to
be executed simply by calling pdfCropMargins, without the .py extension.

"""

from pdfCropMargins import main

if __name__ == "__main__":
    main()

